### ISSUE TITLE
All keypresses ignored when app running, impossible to quit

### ISSUE THREAD

**Issue by pelrun** [g3gg0/flipper-swd_probe#4]
Just tried the app, and while it happily animated it's spinning 3d model, it ignored all keypresses, including any attempt to quit. The only way to regain control was to force a reset with left+back. Not good!

**Comment by g3gg0** [comment]
thanks. since which main firmware version is this happening?
did it work with older versions for you?

**Comment by pelrun** [comment]
I was on 0.95.0 at the time. I actually recovered by updating to 0.96.1 rather than left+back (which I'd forgotten about at the time), and when I attempted running the app again it behaved itself. So it could very well have been an OS bug or a spurious failure - I've used it successfully multiple times since so I'll put it in the "random cosmic ray" pile for the moment and reopen this if it ever shows again.
